#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#
# sudo yabai --load-sa
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config external_bar all:26:0

yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          autofocus
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                on
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config window_border                off
yabai -m config window_border_width          6
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff555555
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               alt
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  06
yabai -m config bottom_padding               06
yabai -m config left_padding                 06
yabai -m config right_padding                06
yabai -m config window_gap                   06


yabai -m signal --add event=space_changed \
  action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-spaces-jsx\"'"

# Keep focus on space when application terminated
yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"


# Floating windows configuration
yabai -m rule --add app="^Firefox$" title="^Opening " manage=off
yabai -m rule --add app="^GIMP-" manage=off
yabai -m rule --add app="^GIMP-" title=" – GIMP$" manage=on
yabai -m rule --add app="^Inkscape$" title="^Select file to open$" manage=off
yabai -m rule --add app="^Inkscape$" title=" - Inkscape$" manage=on

# Load dynamic floating_windows configuration
floating_windows_config="$HOME/.config/yabai/floating_windows"
if [ -f "$floating_windows_config" ]; then
  . "$floating_windows_config"
fi

echo "yabai configuration loaded.."


#echo "ALL ALL = (ALL) NOPASSWD: $(which yabai) --load-sa" | sudo tee /etc/sudoers.d/yabai
sudo yabai --load-sa
echo "yabai scripting addon loaded.."
