# Powerlevel10k prompt configuration.
# Hand-tuned, migrated from .zshrc on 2026-06-02.
# Previous wizard (rainbow) output saved as ~/.p10k.zsh.rainbow-wizard.bak

# Instant prompt: keep it on but stay quiet (no warnings about console output
# produced during init, e.g. by the dock-bounce printf or gitstatus).
typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet

# PowerLevel9K configuration
KUBE_PS1_PREFIX=""
KUBE_PS1_SUFFIX=""
KUBE_PS1_SEPARATOR=""
KUBE_PS1_SYMBOL_ENABLE="false"
KUBE_PS1_DIVIDER=" "

typeset -g POWERLEVEL9K_MODE=nerdfont-complete
typeset -g POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR='%233F\uE0B1'
typeset -g POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR='%233F\uE0B3'
typeset -g POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR='\uE0B0'
typeset -g POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR='\uE0B2'
typeset -g POWERLEVEL9K_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL='\uE0B0'
typeset -g POWERLEVEL9K_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL='\uE0B2'
typeset -g POWERLEVEL9K_LEFT_PROMPT_FIRST_SEGMENT_START_SYMBOL=''
typeset -g POWERLEVEL9K_RIGHT_PROMPT_LAST_SEGMENT_END_SYMBOL=''
typeset -g POWERLEVEL9K_EMPTY_LINE_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL=
typeset -g POWERLEVEL9K_PROMPT_CHAR_BACKGROUND=
typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_{VIINS,VICMD,VIVIS}_FOREGROUND=76
typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_{VIINS,VICMD,VIVIS}_FOREGROUND=196
typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIINS_CONTENT_EXPANSION='❯'
typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VICMD_CONTENT_EXPANSION='❮'
typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIVIS_CONTENT_EXPANSION='Ⅴ'
typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIOWR_CONTENT_EXPANSION='▶'
typeset -g POWERLEVEL9K_PROMPT_CHAR_OVERWRITE_STATE=true
typeset -g POWERLEVEL9K_PROMPT_CHAR_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL=
typeset -g POWERLEVEL9K_PROMPT_CHAR_LEFT_PROMPT_FIRST_SEGMENT_START_SYMBOL=
typeset -g POWERLEVEL9K_PROMPT_CHAR_LEFT_{LEFT,RIGHT}_WHITESPACE=

typeset -g POWERLEVEL9K_DIR_FOREGROUND=015
typeset -g POWERLEVEL9K_DIR_BACKGROUND=239
typeset -g POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_unique
typeset -g POWERLEVEL9K_SHORTEN_DELIMITER=
typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND=015
typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND=015
typeset -g POWERLEVEL9K_DIR_ANCHOR_BOLD=true
local anchor_files=(
  .bzr
  .citc
  .git
  .hg
  .node-version
  .python-version
  .ruby-version
  .shorten_folder_marker
  .svn
  .terraform
  CVS
  Cargo.toml
  composer.json
  go.mod
  package.json
)
typeset -g POWERLEVEL9K_SHORTEN_FOLDER_MARKER="(${(j:|:)anchor_files})"
typeset -g POWERLEVEL9K_SHORTEN_DIR_LENGTH=1
typeset -g POWERLEVEL9K_DIR_MAX_LENGTH=80
typeset -g POWERLEVEL9K_DIR_MIN_COMMAND_COLUMNS=40
typeset -g POWERLEVEL9K_DIR_MIN_COMMAND_COLUMNS_PCT=50
typeset -g POWERLEVEL9K_DIR_HYPERLINK=false
typeset -g POWERLEVEL9K_DIR_SHOW_WRITABLE=true
typeset -g POWERLEVEL9K_DIR_CLASSES=()

typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=3
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND=234
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=234
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_PRECISION=3
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FORMAT='d h m s'

#typeset -g POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
typeset -g POWERLEVEL9K_CONTEXT_TEMPLATE='%B%n%b'

ZLE_RPROMPT_INDENT=0
POWERLEVEL9K_CUSTOM_KUBE_PS1='kube_ps1'

# one line
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir virtualenv background_jobs)
#POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status custom_kube_ps1 vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status command_execution_time kubecontext vcs)

# two lines
#POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir virtualenv newline prompt_char)
#POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status background_jobs custom_kube_ps1 vcs newline)

POWERLEVEL9K_CONTEXT_FOREGROUND='232'
POWERLEVEL9K_CONTEXT_BACKGROUND='184'
#POWERLEVEL9K_DIR_DEFAULT_BACKGROUND='236'
#POWERLEVEL9K_DIR_DEFAULT_FOREGROUND='250'
#POWERLEVEL9K_DIR_HOME_BACKGROUND='236'
#POWERLEVEL9K_DIR_HOME_FOREGROUND='250'
#POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND='236'
#POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND='250'
#POWERLEVEL9K_DIR_ETC_BACKGROUND='052'
#POWERLEVEL9K_DIR_ETC_FOREGROUND='214'
POWERLEVEL9K_CUSTOM_KUBE_PS1_FOREGROUND='233'
POWERLEVEL9K_CUSTOM_KUBE_PS1_BACKGROUND='235'
POWERLEVEL9K_KUBECONTEXT_CLASSES=(
    '*prod*'  PROD
    '*'       DEFAULT)
POWERLEVEL9K_KUBECONTEXT_PROD_BACKGROUND='235'
POWERLEVEL9K_KUBECONTEXT_PROD_FOREGROUND=001
POWERLEVEL9K_KUBECONTEXT_PROD_VISUAL_IDENTIFIER_EXPANSION=''
POWERLEVEL9K_KUBECONTEXT_PROD_CONTENT_EXPANSION+='$P9K_KUBECONTEXT_NAME%6F${${:- $P9K_KUBECONTEXT_NAMESPACE}:# default}'
POWERLEVEL9K_KUBECONTEXT_DEFAULT_BACKGROUND='235'
POWERLEVEL9K_KUBECONTEXT_DEFAULT_FOREGROUND=134
POWERLEVEL9K_KUBECONTEXT_DEFAULT_VISUAL_IDENTIFIER_EXPANSION=''
POWERLEVEL9K_KUBECONTEXT_DEFAULT_CONTENT_EXPANSION+='$P9K_KUBECONTEXT_NAME%6F${${:- $P9K_KUBECONTEXT_NAMESPACE}:# default}'
#POWERLEVEL9K_KUBECONTEXT_PREFIX='⎈ '


## for recordings only
#POWERLEVEL9K_KUBECONTEXT_DEFAULT_CONTENT_EXPANSION='$P9K_KUBECONTEXT_NAMESPACE ⎈'
#POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status command_execution_time kubecontext)

#POWERLEVEL9K_VCS_BACKGROUND='112'
#POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='214'
POWERLEVEL9K_VCS_FOREGROUND='148'
POWERLEVEL9K_VCS_BACKGROUND='236'
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='214'
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='236'
POWERLEVEL9K_STATUS_BACKGROUND='234'
POWERLEVEL9K_STATUS_OK=false
POWERLEVEL9K_STATUS_OK_FOREGROUND=70
POWERLEVEL9K_STATUS_OK_VISUAL_IDENTIFIER_EXPANSION='✔'
POWERLEVEL9K_STATUS_OK_PIPE=true
POWERLEVEL9K_STATUS_OK_PIPE_FOREGROUND=70
POWERLEVEL9K_STATUS_OK_PIPE_VISUAL_IDENTIFIER_EXPANSION='✔'
POWERLEVEL9K_STATUS_ERROR_FOREGROUND=160
POWERLEVEL9K_STATUS_ERROR_VISUAL_IDENTIFIER_EXPANSION='↵'
POWERLEVEL9K_STATUS_ERROR_SIGNAL=true
POWERLEVEL9K_STATUS_ERROR_SIGNAL_FOREGROUND=160
POWERLEVEL9K_STATUS_VERBOSE_SIGNAME=false
POWERLEVEL9K_STATUS_ERROR_SIGNAL_VISUAL_IDENTIFIER_EXPANSION='↵'
POWERLEVEL9K_STATUS_ERROR_PIPE=true
POWERLEVEL9K_STATUS_ERROR_PIPE_FOREGROUND=160
POWERLEVEL9K_STATUS_ERROR_PIPE_VISUAL_IDENTIFIER_EXPANSION='↵'
POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND='236'
